version: '3'
services:
    db:
        image: postgres:10
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db