default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: 

production:
  <<: *default
  database: app_production

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
